### PR TITLE
Fixed issue of MaxNestedChildren to work with latest HtmlAgilityPack.

### PR DESCRIPTION
**Pull request by maozoomd**
Fixed issue of MaxNestedChildren to work with latest HtmlAgilityPack version that exposes OptionFixNestedTags property.

Had to fix the tests as now the parsing succeeds ( with no StackOverflowException)

### CODE REVIEW

**Comment by sjdirect** [comment]
An observation of why this might be failing. If you look at the last successful builds tests here...
https://ci.appveyor.com/project/sjdirect/abot/build/1.5.1.69/tests

And search on the page for "HtmlDocument_ToManyNested". You will see a passing test. If you look at the test result from your pull request code... 
https://ci.appveyor.com/project/sjdirect/abot/build/1.5.1.71/tests

And search for "HtmlDocument_ToManyNested" you will see its yellow and shows an empty time even though it is NOT ignored. I suspect that this test is causing the nunit process to choke and fail. A likely explanation is that when running the tests on your machine, it works fine but when running on lower resource machine (like the one used for the FREE build server) there are stack/memory issues.

**Comment by maozoomd** [comment]
Then maybe this test can be marked as [Ignore], because it does pass.

**Comment by sjdirect** [comment]
We can't ignore the test since anyone running crawlers on lower end hardware would then have to deal with full blown process crashes. I believe that is unacceptable in a library.

**Comment by maozoomd** [comment]
Found another fix without changing the tests

**Comment by DickBaker** [comment]
Steven, Hi. Replying to my PR you stated that my #161 PR failed (yellow/blank) on
https://ci.appveyor.com/project/sjdirect/abot/build/1.5.1.71/tests

but that link shows success (albeit 8 seconds elapsed). You passed that same link to maozoomd
so perhaps you meant to show me instead the later run (blank duration) ?
https://ci.appveyor.com/project/sjdirect/abot/build/1.5.1.72/tests

Tests certainly all passed on my laptop, but I accept ruling that no UT should endanger minimal h/w.

Am keen that you should take advantage of the refactoring guidance by the roslynator extension, so can try again or suggest you take a sniff yourself.
abot_161_passes

My main surprise was that I got a permission error trying to upload that PR, but maybe the upload completed ok but wouldn't merge into master (fair enuff) ? Pls tell me how to conduct future PR without error. ta

**Comment by sjdirect** [comment]
Unfortunately, i do not have time to invest in this at the moment. I'll leave it open for when I can. Like I mentioned in another thread, I may remove HAP completely in favor of AngleSharp. Thanks for the effort.

**Pull request closed without merging**
