### PR TITLE
Fire event on robots txt parse complete

### PR DESCRIPTION
**Pull request by vovikdrg**
I did it but i dont like that i exposed RobotsDotText with Robots, to do in better way i wold probably need to change a bit more code. Let me know what you think

### CODE REVIEW

**Comment by sjdirect** [comment]
Looks good. I'll be able to take a closer look in the next few days and hopefully get it integrated soon. Thanks!

**Comment by sjdirect** [comment]
The build failed because the PoliteWebCrawler.cs file on line 184 you used the new null condition operator "?.". Abot targets .net 4.0 which does not support that feature. Can you change it to regular null check to the build can run? I would do this myself but then you would lose credit for your work on this pull request.

**Comment by vovikdrg** [comment]
Yes i will fix it today

**Comment by vovikdrg** [comment]
Besides that i dont like that i have opened IRobots.
I think i will change it a bit _robotsDotTextFinder.Find(uri); should return IRobots and than from it RobotDotText should be created. Because opening encapsulated field its a bit bad idea. 

Any way today will push new changes

**Comment by sjdirect** [comment]
Sounds good

**Comment by vovikdrg** [comment]
To rewrite as i thought it require a lot of thing to change, so i am not sure if should i do that.

**Comment by sjdirect** [comment]
Thanks. One of the nicer pull requests I've had. Very clean and I appreciate the tests as well.

**Pull request merged**
