### PR TITLE
Icc refactor

### PR DESCRIPTION
**Pull request by knoxv1lle**
Now with the correct project file.

### CODE REVIEW

**Comment by knoxv1lle** [comment]
2nd time lucky. 

The reason for moving the poco to an interface is so that the configuration items can be extended with interface inheritance rather than concrete inheritance. 

I have a need to add additional items to the CrawlConfig (creating my own POCO). I want to ensure that the core has all the properties (defined by the interface contract), and extend my own type with additional members. The derived type I am creating may well have lots of additional properties, and serialization logic that should be abstracted by the newly added interface. 

This pattern already appears to be used with ICrawlDecissionMaker, IPageRequester etc.

**Comment by sjdirect** [comment]
I like your argument more today:) However, the ICrawlDecisionMaker and IPageRequester interfaces exist because those implementations have behavior, not just simple properties. Changing the dependency signatures to ICrawlConfiguration would break existing user's custom code. This would require changing the version to 1.5.x to spotlight the breaking changes. At this moment I dont think the addition is enough to justify all that.

However, thank you for your contribution. I know it takes time and effort to prepare these pull requests.

**Comment by knoxv1lle** [comment]
I'm kind of convinced that it's not going to break backward compatibility. Please correct me if I have missed something.

1) If a user has added an instance of CrawlConfig then this will still work (CrawlConfig implements the interface). 
2) If the user has derived from CrawlConfig and used their new object, that will also still work as the base type will still implement the interface.

**Comment by sjdirect** [comment]
Sorry, you are absolutely correct. Your change would be backward compatible. However, I still cannot accept the pull request due to my belief that pocos should not implement an interface. It would be a one-off since all the other pocos do not follow this pattern. I understand and respect your argument though.

Thanks!

**Pull request closed without merging**
