### PR TITLE
Use HtmlDocument.MaxDepthLevel from latest HAP to replace local fix.

### PR DESCRIPTION
**Pull request by maozoomd**
HtmlDocument.MaxDepthLevel behaves the same as OptionMaxNestedChildNodes  and throws a catch-able exception rather than the problematic stackoverflowexception.

### CODE REVIEW

**Comment by maozoomd** [comment]
How did you come up with the number 5000 for max children? It seems like the built in fix gets thrown by the build before...

**Comment by sjdirect** [comment]
I don't remember, I did that patch over 3 years ago. Like I mentioned there have been a few efforts to get onto the standard nuget package version of HAP. All of those failed. I'm beginning to think that I will remove HAP completely and just use AngleSharp as the default implementation.

**Comment by maozoomd** [comment]
We use HAP internally, so it is in my interest to try solve this ☺
I’m trying to configure my own build (with AppVeyor) for the branch I created, but it keeps on failing on .Net version issues.
Can you suggest any special environment configuration you’ve set for the build?

Thanks,
Maoz

**Comment by sjdirect** [comment]
Nothing special, 

Build worker image: Visual Studio 2015, 

Before build script:
nuget restore
git submodule init 
git submodule update

Solution:
Abot.sln

**Comment by sjdirect** [comment]
Hap is no longer supported

**Pull request closed without merging**
