### PR TITLE
add README_Chinese.md

### PR DESCRIPTION
**Pull request by zixiliuyue**
I found almost no information on Chinese use of the process, put the README file according to their own understanding of the translation a bit.

### CODE REVIEW

**Comment by sjdirect** [comment]
Hi, 

My worry is that when I add/change documentation this will get out of sync since I have no way to translate myself. I assume any browser based tools do not do a good job of translating on the fly. Is that correct?

**Comment by zixiliuyue** [comment]
Oh, I do not consider that much. . . I am sorry

**Comment by sjdirect** [comment]
Don't apologize. I appreciate the effort. Maybe you can host the readme file on a repo and I can link to it from Abot's homepage. Something like "Here is the unofficial Chinese documentation". That way its handled and maintained separate with its own section for issue tracking.

**Comment by zixiliuyue** [comment]
ooh , I fock this project ([Abot](https://github.com/zixiliuyue/abot)), but I do not request the merger.

**Comment by sjdirect** [comment]
Can you please remove the code. Just have a project with the readme that
links to my repo. I dont want people getting old code.

Thanks!!!

**Comment by zixiliuyue** [comment]
yes, i can. @sjdirect

**Comment by sjdirect** [comment]
I added a link from the abot github page to your docs. Search for
"Unofficial Chinese Documentation" on that page to see it. Thanks for
contributing!

**Pull request closed without merging**
