### PR TITLE
Update HtmlAgilityPack

### PR DESCRIPTION
**Pull request by andy-williams**
https://htmlagilitypack.codeplex.com/SourceControl/changeset/108454

AgilityPack has now been updated to resolve the stackoverflow issue. We no longer need the stackoverflow issue workaround.

- updated HtmlAgilityPack to 1.4.9.5
- remove redundant HtmlAgilityPack binary
- updated some tests to reflect change

### CODE REVIEW

**Comment by andy-williams** [comment]
The StackOverflowException discussion for reference:

https://code.google.com/archive/p/abot/issues/77

**Comment by sjdirect** [comment]
@andy-williams your pull request shows that this issue was not fixed with that version. See the [bottom of this page](https://ci.appveyor.com/project/sjdirect/abot/build/1.5.1.44) which is the build result from your pull request. That is what happens when a stackoverflow exception happens due to the hap problem.

**Comment by andy-williams** [comment]
Perhaps I misread the commit in HAP. I see that this is quite historic though - did you raise this with the author of HAP previously? If not, I'll try to submit a patch for the HAP project.

**Comment by sjdirect** [comment]
I did try to get this fixed but HAP appears to be unmaintained and there have been several unofficial forks. Also it appears that many of HAPs internals rely on stacks so there are many ways to make it blow up. I just happened to find 1 and my patch fixed it but maybe not other ways. Others have fixed some of the other ways but not my problem, etc.. etc...

**Pull request closed without merging**
