### PR TITLE
Feature implementation of network Authentication in configuration file

### PR DESCRIPTION
**Pull request by obender**
Feature implementation of network Authentication in configuration file
*Notes* 
 Implementation of Feature #37
https://github.com/sjdirect/abot/issues/37

Added new section on App.config called
<authorization  />

### CODE REVIEW

**Comment by sjdirect** [comment]
Thanks, i'll take a look in the next few days

**Comment by sjdirect** [comment]
Thanks for the contribution!

**Comment by zixiliuyue** [comment]
I see  App.config  <authorization isAlwaysLogin="true" loginUser="test" loginPassword="dummyPass" />，But I can only use IP login website, no user and password, this is my first contact with the reptile, interesting.I finally talked to the foreigner.  0.0

**Comment by obender** [comment]
What do you mean by "IP login website"?

**Comment by zixiliuyue** [comment]
Library of our school！！

**Comment by zixiliuyue** [comment]
Tonight I'll try to combine the HttpWebRequest object request to see the results.  0.0

**Comment by glen-cote** [comment]
In have edited App.config like so: 

`isSendingCookiesEnabled="true"`

```
<authorization
      isAlwaysLogin="true"
      loginUser="myusername"
      loginPassword="mypassword" />
```

and I still cannot crawl past the login page of my site. I've read up on what other people have done for days now and still cannot figure out what I am doing wrong. If you are reading this and have some insight, please assist.

**Comment by sjdirect** [comment]
This will not login using a site specific login form. Its using basic authentication which is not used on most websites. Logging into a website is a custom job every time. Every website is different.

**Comment by glen-cote** [comment]
Thank you for replying.

I found this google form: https://groups.google.com/forum/#!topic/abot-web-crawler/2eSqx_tS_wQ written by you. 

Would you say these 5 steps are accurate for getting past a login page to crawl?

> 1) Extend the Abot.Core.PageRequester class and override the MakeRequest() method
> 2) Copy the overridden code as the starting point for your new impl of MakeRequest()
> 3) Modify the HttpWebRequest object to use the credentials you want to use 
> 4) After you receive the first response, you will likely need to save the cookie that you get back and resend it with all future http requests otherwise you will have have to login again. 
> 5) Pass your new class into the WebCrawler.cs constructor so Abot knows to use your implementation 

I have tried this as well but have not succeeded.

**Comment by sjdirect** [comment]
That approach does still sound to be accurate. If you are doing those steps you are likely close.

**Comment by glen-cote** [comment]
So I understand now that the code has to be custom for every website that has a login page. I am confused as to what those customs should be. I have looked at my web traffic to the site I'm trying to crawl with Fiddler, but I can't make sense of the data I'm seeing. I have been reading search results for for "C# webrequest login" but am left confused. What variables should I be accounting for in general? I tried to save the cookies from my first response and then pass it to the crawler, but along the way the cookies are lost. I would do that with every possible site I can think of with a login page.

If you have a particular guide you like or maybe a different search I could type into Google, that would help tremendously. 

Here is how I've tried to override the MakeRequest function.

```
public override CrawledPage MakeRequest(Uri uri, Func<CrawledPage, CrawlDecision> shouldDownloadContent)
            {
                if (uri == null)
                    throw new ArgumentNullException("uri");

                HttpWebRequest login_request = BuildRequestObject(uri);
                HttpWebResponse login_response = null;
                CookieContainer myCookieContainer = new CookieContainer();

                string userName = "username";
                string password = "password";
                
                ASCIIEncoding encoding = new ASCIIEncoding();
                string postData = "Username=" + userName + "&Password=" + password;
                byte[] postDataBytes = encoding.GetBytes(postData);

                //maybe more variables have to be accounted for?
                login_request.Method = "POST";
                login_request.ContentType = "application/x-www-form-urlencoded";
                login_request.ContentLength = postDataBytes.Length;
                login_request.CookieContainer = myCookieContainer;

                using (var stream = login_request.GetRequestStream())
                {
                    Console.WriteLine("Writing to stream");
                    stream.Write(postDataBytes, 0, postDataBytes.Length);
                    stream.Close();
                }

                login_response = (HttpWebResponse)login_request.GetResponse();

                //add cookies to cookiecontainer
                myCookieContainer.Add(login_response.Cookies);
              
                CrawledPage crawledPage = new CrawledPage(uri);

                HttpWebRequest request = null;
                HttpWebResponse response = null;
                try
                {
                    request = BuildRequestObject(uri);
                    crawledPage.RequestStarted = DateTime.Now;
                    
                    request.CookieContainer = myCookieContainer;
                                        
                    response = (HttpWebResponse)request.GetResponse();

                    //I'd think that the response would have gotten the cookies by because the request.CookieContainer had cookies in it
                    
                    ProcessResponseObject(response);
                }
                catch (WebException e)
                {
                    crawledPage.WebException = e;

                    if (e.Response != null)
                        response = (HttpWebResponse)e.Response;

                    _logger.DebugFormat("Error occurred requesting url [{0}]", uri.AbsoluteUri);
                    _logger.Debug(e);
                }
                catch (Exception e)
                {
                    _logger.DebugFormat("Error occurred requesting url [{0}]", uri.AbsoluteUri);
                    _logger.Debug(e);
                }
                finally
                {
                    try
                    {
                        crawledPage.HttpWebRequest = request;

                        //I'd think the crawledPage would have the cookies now

                        crawledPage.RequestCompleted = DateTime.Now;
                        if (response != null)
                        {
                            crawledPage.HttpWebResponse = new HttpWebResponseWrapper(response);

                            //cookies deformed by now, most gone                        

                            CrawlDecision shouldDownloadContentDecision = shouldDownloadContent(crawledPage);
                            if (shouldDownloadContentDecision.Allow)
                            {
                                crawledPage.DownloadContentStarted = DateTime.Now;
                                crawledPage.Content = _extractor.GetContent(response);
                                crawledPage.DownloadContentCompleted = DateTime.Now;
                            }
                            else
                            {
                                _logger.DebugFormat("Links on page [{0}] not crawled, [{1}]", crawledPage.Uri.AbsoluteUri, shouldDownloadContentDecision.Reason);
                            }

                            response.Close();//Should already be closed by _extractor but just being safe
                        }
                    }
                    catch (Exception e)
                    {
                        _logger.DebugFormat("Error occurred finalizing requesting url [{0}]", uri.AbsoluteUri);
                        _logger.Debug(e);
                    }
                return crawledPage;
            }

```

**Pull request merged**
