### PR TITLE
Disposables, url fragment and tweaks

### PR DESCRIPTION
**Pull request by mikegron**
Changes:

1. Disposables
Added the IDisposable interface to PageRequester, Scheduler, WebContentExtractor and WebCrawler. This is useful when you have custom modules that needs to be disposed correctly!

2. Url fragment
Added  new parameter to the HyperlinkParser to remove or not the url fragment on each link ie everything after the "#" in the url. This is useful when a website keeps relevant data here, for instance single-page apps do this. I've kept the default behaviour of removing it!

3. WebContentExtractor
I've changed some methods in the WebContentExtractor to make them protected and overridable to be able to make a custom content extractor while still reusing the same GetCharsetFromBody and GetEncoding methods. GetCharsetFromBody now takes an input string because our custom WebContentExtractor downloads a string directly (no stream), and it does not affect the behaviour.

4. Root Uri validation
If you try to crawl with a root uri that gets redirected on the first call, nothing will be crawled. For instance, "http://dotnetperls.com/" redirects to "http://www.dotnetperls.com/". The redirection works but the redirected page is now considered external since it is on another authority than the starting address. To fix this we validate the root page, checking if the page was redirected and changing the RootUri if it was. Then, we consider links to "dotnetperls.com" and "www.dotnetperls.com" to be internal (since the website can have mixed links too).

All of this was thoroughly tested in our environment. If you have any questions just let me know!

### CODE REVIEW

**Comment by sjdirect** [comment]
Thanks for your contribution. Very clean changes and I appreciate the added unit tests.

**Comment by sjdirect** [comment]
See my last push https://github.com/sjdirect/abot/commit/eb719d8476d8c66edab78779bc1deffd86747b29. A few changes to what you had. Added the removeUrlFragment (now called isRespectUrlNamedAnchorOrHashbangEnabled) to the config file. Also added a few more unit tests.

**Comment by LeMoussel** [comment]
@sjdirect I post a note on Abot/Core/HyperLinkParser.cs. with an another way  to remove Url fragment.

**Comment by sjdirect** [comment]
Thanks LeMoussel. I replied inline to that note.

**Pull request merged**
